version: "2.1"

services:
    cms-db:
        image: mysql:8.4
        volumes:
            - type: bind
              source: ./shared/db
              target: /var/lib/mysql:Z"
              is_directory: true
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-cms}
            - MYSQL_USER=${MYSQL_USER:-cms}
            - MYSQL_PASSWORD=${SERVICE_PASSWORD_DATABASE}
            - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:-yes}
        mem_limit: 1g
        restart: always
    cms-xmr:
        image: ghcr.io/xibosignage/xibo-xmr:1.2
        restart: always
        mem_limit: 256m
    cms-web:
        image: ghcr.io/xibosignage/xibo-cms:release-4.4.1
        volumes:
            - type: bind
              source: ./shared/cms/custom
              target: /var/www/cms/custom:Z"
              is_directory: true
            - type: bind
              source: ./shared/backup
              target: /var/www/backup:Z"
              is_directory: true
            - type: bind
              source: ./shared/cms/web/theme/custom
              target: /var/www/cms/web/theme/custom:Z"
              is_directory: true
            - type: bind
              source: ./shared/cms/library
              target: /var/www/cms/library:Z"
              is_directory: true
            - type: bind
              source: ./shared/cms/web/userscripts
              target: /var/www/cms/web/userscripts:Z"
              is_directory: true
            - type: bind
              source: ./shared/cms/ca-certs
              target: /var/www/cms/ca-certs:Z"
              is_directory: true
        restart: always
        environment:
            - SERVICE_URL_CMS_WEB
            - MYSQL_HOST=${MYSQL_HOST:-cms-db}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-cms}
            - MYSQL_USER=${MYSQL_USER:-cms}
            - MYSQL_PASSWORD=${SERVICE_PASSWORD_DATABASE}
            - XMR_HOST=${XMR_HOST:-cms-xmr}
            - CMS_USE_MEMCACHED=${CMS_USE_MEMCACHED:-true}
            - MEMCACHED_HOST=${MEMCACHED_HOST:-cms-memcached}
            - CMS_SMTP_SERVER=${CMS_SMTP_SERVER}
            - CMS_SMTP_USERNAME=${CMS_SMTP_USERNAME}
            - CMS_SMTP_PASSWORD=${CMS_SMTP_PASSWORD}
            - CMS_SMTP_USE_TLS=${CMS_SMTP_USE_TLS:-yes}
            - CMS_SMTP_USE_STARTTLS=${CMS_SMTP_USE_STARTTLS:-no}
            - CMS_SMTP_REWRITE_DOMAIN=${CMS_SMTP_REWRITE_DOMAIN:-none}
            - CMS_SMTP_HOSTNAME=${CMS_SMTP_HOSTNAME}
            - CMS_SMTP_FROM_LINE_OVERRIDE=${CMS_SMTP_FROM_LINE_OVERRIDE}
            - CMS_SMTP_FROM=${CMS_SMTP_FROM}
            - CMS_SERVER_NAME=${SERVICE_FQDN_CMS_WEB}
        mem_limit: 1g
    cms-memcached:
        image: memcached:alpine
        command: memcached -m 15
        restart: always
        mem_limit: 100M
    cms-quickchart:
      image: ianw/quickchart
      restart: always
